"""add documents and knowledge_chunks

Revision ID: 0388beb0f528
Revises: 2ede5e7375d5
Create Date: 2026-09-05 21:55:13.617236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '0388beb0f528'
down_revision: Union[str, Sequence[str], None] = '2ede5e7375d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('embedding_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_clinic_id'), 'documents', ['clinic_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('clinic', 'location', 'doctor', 'treatment', 'document', name='knowledge_source_type'), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_clinic_id'), 'knowledge_chunks', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_source_id'), 'knowledge_chunks', ['source_id'], unique=False)
    # NOTE: autogenerate also proposed dropping+recreating clinic_staff's
    # user_id -> auth.users FK here — the same false diff explained in
    # 2ede5e7375d5_add_visitor_sessions.py (the ORM model doesn't declare
    # it, so autogenerate can't see it already exists). Intentionally
    # omitted.
    # ### end Alembic commands ###

    op.create_index(
        'ix_knowledge_chunks_embedding_hnsw',
        'knowledge_chunks',
        ['embedding'],
        unique=False,
        postgresql_using='hnsw',
        postgresql_with={'m': 16, 'ef_construction': 64},
        postgresql_ops={'embedding': 'vector_cosine_ops'},
    )

    op.execute(
        """
        CREATE TRIGGER set_updated_at
        BEFORE UPDATE ON documents
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at();
        """
    )

    _enable_rls()


def _enable_rls() -> None:
    # Same pattern as the initial migration's _DIRECT_CLINIC_TABLES — both
    # tables have a direct clinic_id column, scoped by clinic_staff
    # membership via the is_clinic_staff() function that migration created.
    for table in ('documents', 'knowledge_chunks'):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(
            f"""
            CREATE POLICY clinic_staff_access ON {table}
            FOR ALL
            USING (is_clinic_staff(clinic_id))
            WITH CHECK (is_clinic_staff(clinic_id));
            """
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_chunks_source_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_clinic_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_documents_clinic_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###

    op.execute("DROP TYPE IF EXISTS knowledge_source_type;")
