"""add visitor_sessions

Revision ID: 2ede5e7375d5
Revises: cd86074a1866
Create Date: 2026-09-05 21:37:21.432024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ede5e7375d5'
down_revision: Union[str, Sequence[str], None] = 'cd86074a1866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor_sessions',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('treatment_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('campaign', sa.String(length=200), nullable=True),
    sa.Column('landing_page', sa.String(length=500), nullable=True),
    sa.Column('anonymous_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_sessions_anonymous_id'), 'visitor_sessions', ['anonymous_id'], unique=False)
    op.create_index(op.f('ix_visitor_sessions_clinic_id'), 'visitor_sessions', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_visitor_sessions_treatment_id'), 'visitor_sessions', ['treatment_id'], unique=False)
    # NOTE: autogenerate also proposed dropping+recreating clinic_staff's
    # user_id -> auth.users FK here. That's a false diff — the ORM model
    # deliberately doesn't declare that FK (see models/clinic.py), so
    # autogenerate can't see it in the DB-only constraint and assumes it's
    # new. The constraint already exists from the initial migration;
    # touching it here would be a no-op at best and a risky drop of a real
    # cascade-delete constraint at worst, so it's intentionally omitted.
    # ### end Alembic commands ###

    _enable_visitor_sessions_rls()


def _enable_visitor_sessions_rls() -> None:
    # Same pattern as the initial migration's _DIRECT_CLINIC_TABLES — a
    # direct clinic_id column, scoped by clinic_staff membership via the
    # is_clinic_staff() function that migration created.
    op.execute("ALTER TABLE visitor_sessions ENABLE ROW LEVEL SECURITY;")
    op.execute(
        """
        CREATE POLICY clinic_staff_access ON visitor_sessions
        FOR ALL
        USING (is_clinic_staff(clinic_id))
        WITH CHECK (is_clinic_staff(clinic_id));
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitor_sessions_treatment_id'), table_name='visitor_sessions')
    op.drop_index(op.f('ix_visitor_sessions_clinic_id'), table_name='visitor_sessions')
    op.drop_index(op.f('ix_visitor_sessions_anonymous_id'), table_name='visitor_sessions')
    op.drop_table('visitor_sessions')
    # ### end Alembic commands ###
