"""initial schema

Revision ID: cd86074a1866
Revises: 
Create Date: 2026-09-05 20:06:28.157120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd86074a1866'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('primary_phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('timezone', sa.String(length=50), server_default='Asia/Dubai', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='onboarding', nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinic_locations',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinic_locations_clinic_id'), 'clinic_locations', ['clinic_id'], unique=False)
    op.create_table('clinic_staff',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='staff', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment=(
        "user_id references auth.users (Supabase's own schema, in the same "
        "Postgres instance) — deleting the auth user cascades here."
    )
    )
    op.create_index(op.f('ix_clinic_staff_clinic_id'), 'clinic_staff', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_clinic_staff_user_id'), 'clinic_staff', ['user_id'], unique=False)
    op.create_table('doctors',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('specialties', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('credentials', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_clinic_id'), 'doctors', ['clinic_id'], unique=False)
    op.create_table('treatments',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('approved_information', sa.Text(), nullable=True),
    sa.Column('faq', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price_guidance', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('booking_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatments_clinic_id'), 'treatments', ['clinic_id'], unique=False)
    op.create_table('leads',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('whatsapp', sa.String(length=50), nullable=True),
    sa.Column('treatment_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('landing_page', sa.String(length=500), nullable=True),
    sa.Column('preferred_time', sa.String(length=200), nullable=True),
    sa.Column('intent_score', sa.Integer(), nullable=True),
    sa.Column('consent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONTACTING', 'CONTACTED', 'QUALIFIED', 'APPOINTMENT_INTENT', 'BOOKED', 'CONFIRMED', 'ATTENDED', 'NO_ANSWER', 'WHATSAPP_FOLLOWUP', 'HUMAN_REQUIRED', 'CANCELLED', 'NO_SHOW', 'LOST', 'REACTIVATION', name='lead_status'), server_default='NEW', nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_clinic_id'), 'leads', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('ix_leads_treatment_id'), 'leads', ['treatment_id'], unique=False)
    op.create_table('appointments',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=True),
    sa.Column('treatment_id', sa.Uuid(), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'booked', 'confirmed', 'cancelled', 'completed', 'no_show', name='appointment_status'), server_default='pending', nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_clinic_id'), 'appointments', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_external_id'), 'appointments', ['external_id'], unique=False)
    op.create_index(op.f('ix_appointments_lead_id'), 'appointments', ['lead_id'], unique=False)
    op.create_index(op.f('ix_appointments_start'), 'appointments', ['start'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index(op.f('ix_appointments_treatment_id'), 'appointments', ['treatment_id'], unique=False)
    op.create_table('consents',
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_lead_id'), 'consents', ['lead_id'], unique=False)
    op.create_table('conversations',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('voice', 'whatsapp', 'web_chat', name='conversation_channel'), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='active', nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_clinic_id'), 'conversations', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_conversations_external_id'), 'conversations', ['external_id'], unique=False)
    op.create_index(op.f('ix_conversations_lead_id'), 'conversations', ['lead_id'], unique=False)
    op.create_table('appointment_events',
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_events_appointment_id'), 'appointment_events', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_events_timestamp'), 'appointment_events', ['timestamp'], unique=False)
    op.create_table('events',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('appointment_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_appointment_id'), 'events', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_events_clinic_id'), 'events', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_lead_id'), 'events', ['lead_id'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='message_direction'), nullable=False),
    sa.Column('sender_type', sa.Enum('patient', 'ai', 'staff', name='message_sender_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_external_id'), 'messages', ['external_id'], unique=False)
    # ### end Alembic commands ###

    _create_updated_at_triggers()
    _enable_row_level_security()


# Tables with an `updated_at` column that should be kept in sync by the DB
# itself (see docs/DATABASE.md) rather than relying on every writer to
# remember to set it.
_TABLES_WITH_UPDATED_AT = (
    'clinics', 'clinic_locations', 'clinic_staff', 'doctors', 'treatments',
    'leads', 'appointments', 'consents', 'conversations', 'messages',
)


def _create_updated_at_triggers() -> None:
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = clock_timestamp();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table in _TABLES_WITH_UPDATED_AT:
        op.execute(
            f"""
            CREATE TRIGGER set_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW
            EXECUTE FUNCTION set_updated_at();
            """
        )


# Row-Level Security is a defense-in-depth backstop (CLAUDE.md §23):
# apps/api connects with the `postgres` role, which bypasses RLS entirely,
# and is the only writer in this architecture (docs/ARCHITECTURE.md) — RLS
# protects against a *future* mistake, e.g. a direct Supabase client query
# added to apps/web, not against anything in today's request path.
#
# Tables with a direct clinic_id column are scoped by clinic_staff
# membership; child tables without one are scoped via a join to their
# parent's clinic_id. `clinics` itself has no clinic_id column — it's
# scoped by its own `id` instead.
_DIRECT_CLINIC_TABLES = (
    'clinic_locations', 'doctors', 'treatments', 'leads',
    'appointments', 'conversations', 'events',
)

_CHILD_TABLE_POLICIES = {
    'consents': (
        "EXISTS (SELECT 1 FROM leads l WHERE l.id = consents.lead_id "
        "AND is_clinic_staff(l.clinic_id))"
    ),
    'messages': (
        "EXISTS (SELECT 1 FROM conversations c WHERE c.id = messages.conversation_id "
        "AND is_clinic_staff(c.clinic_id))"
    ),
    'appointment_events': (
        "EXISTS (SELECT 1 FROM appointments a WHERE a.id = appointment_events.appointment_id "
        "AND is_clinic_staff(a.clinic_id))"
    ),
    'clinic_staff': "user_id = auth.uid()",
}


def _enable_row_level_security() -> None:
    op.execute(
        """
        CREATE OR REPLACE FUNCTION is_clinic_staff(target_clinic_id uuid)
        RETURNS boolean AS $$
            SELECT EXISTS (
                SELECT 1 FROM clinic_staff cs
                WHERE cs.clinic_id = target_clinic_id AND cs.user_id = auth.uid()
            );
        $$ LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public;
        """
    )

    op.execute("ALTER TABLE clinics ENABLE ROW LEVEL SECURITY;")
    op.execute(
        """
        CREATE POLICY clinic_staff_access ON clinics
        FOR ALL
        USING (is_clinic_staff(id))
        WITH CHECK (is_clinic_staff(id));
        """
    )

    for table in _DIRECT_CLINIC_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(
            f"""
            CREATE POLICY clinic_staff_access ON {table}
            FOR ALL
            USING (is_clinic_staff(clinic_id))
            WITH CHECK (is_clinic_staff(clinic_id));
            """
        )

    op.execute("ALTER TABLE clinic_staff ENABLE ROW LEVEL SECURITY;")
    for table, using_clause in _CHILD_TABLE_POLICIES.items():
        if table == 'clinic_staff':
            op.execute(
                f"""
                CREATE POLICY self_access ON {table}
                FOR ALL
                USING ({using_clause})
                WITH CHECK ({using_clause});
                """
            )
            continue
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(
            f"""
            CREATE POLICY clinic_staff_access ON {table}
            FOR ALL
            USING ({using_clause})
            WITH CHECK ({using_clause});
            """
        )


def downgrade() -> None:
    """Downgrade schema."""
    # CASCADE: RLS policies and triggers on the tables below depend on these
    # functions, and DROP TABLE alone doesn't drop a function itself — order
    # relative to the table drops doesn't matter with CASCADE.
    op.execute("DROP FUNCTION IF EXISTS is_clinic_staff(uuid) CASCADE;")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at() CASCADE;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_external_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_lead_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_clinic_id'), table_name='events')
    op.drop_index(op.f('ix_events_appointment_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_appointment_events_timestamp'), table_name='appointment_events')
    op.drop_index(op.f('ix_appointment_events_appointment_id'), table_name='appointment_events')
    op.drop_table('appointment_events')
    op.drop_index(op.f('ix_conversations_lead_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_external_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_clinic_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_consents_lead_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_appointments_treatment_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_start'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_lead_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_external_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_clinic_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_leads_treatment_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_clinic_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_treatments_clinic_id'), table_name='treatments')
    op.drop_table('treatments')
    op.drop_index(op.f('ix_doctors_clinic_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_clinic_staff_user_id'), table_name='clinic_staff')
    op.drop_index(op.f('ix_clinic_staff_clinic_id'), table_name='clinic_staff')
    op.drop_table('clinic_staff')
    op.drop_index(op.f('ix_clinic_locations_clinic_id'), table_name='clinic_locations')
    op.drop_table('clinic_locations')
    op.drop_table('clinics')
    # ### end Alembic commands ###

    # Enum TYPEs are separate DB objects — dropping the table that used one
    # does not drop the type itself, so it must be done explicitly or a
    # future upgrade fails with "type already exists".
    for enum_type in (
        'lead_status', 'appointment_status', 'conversation_channel',
        'message_direction', 'message_sender_type',
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_type};")
